aws:
  region: us-east-1
  credentials:
    access-key: test
    secret-key: test
  endpoint: http://localhost:4566
  sqs:
    queue-url: http://localhost:4566/000000000000/notification-queue
spring:
  mail:
    host: 127.0.0.1
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
